### ISSUE TITLE
Apple ARM

### ISSUE THREAD

**Issue by Czaki** [conda-forge/imagecodecs-feedstock#12]
There are plans to support ARM for new Apple hardware? As a person who creates wheels for imagecodecs I look for a person with experience with build imagecodecs dependencies on ARM.

**Comment by hmaarrfk** [comment]
Hey @Czaki good to see you.

We are going through the motions, remind me to explicitly add this to the migrator. 

Would you be looking to build your wheels from within a condo environment?

**Comment by Czaki** [comment]
> We are going through the motions, remind me to explicitly add this to the migratory.

Thanks

> Would you be looking to build your wheels from within a condo environment?

I'm not sure. Till now I build dependencies from scratch. But I do not have access to ARM MacOS machine, so If I meet some problem It could be hard to debug it. Also, I have access to a single MacOS machine and read about multiple problems with Python on BigSur, so currently, I do not want to upgrade the system. 

So maybe, at some moment migrate to conda libraries will be a good idea. 

I will start my job after https://github.com/joerick/cibuildwheel/issues/473 is done.

**Comment by hmaarrfk** [comment]
Please follow

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1023

And https://conda-forge.org/status

**Comment by hmaarrfk** [comment]
ok, lol, this recipe has already been migrated to osx-arm

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/imagecodecs-feedstock/pull/11

**Comment by hmaarrfk** [comment]
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by jakirkham** [comment]
> ok, lol, this recipe has already been migrated to osx-arm

So I guess we can close then, right? Does anyone in this thread have access to this hardware to try this on?

**Comment by hmaarrfk** [comment]
I'll let czaki close the issue in case he needs any more help getting things off the ground.
