### ISSUE TITLE
Large package size due to test binary data

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/imagecodecs-feedstock#28]
I noticed that this installer is quite large due to the inclusion of test data.

Would it be acceptable to remove the test data from this package?

![image](https://user-images.githubusercontent.com/90008/114322853-5b541e00-9af0-11eb-998b-a05d6227dce9.png)

It takes about 17MB of the 26MB package.

**Comment by hmaarrfk** [comment]
I just removed the testing phase.

**Comment by jakirkham** [comment]
Could run the tests during the build

**Comment by hmaarrfk** [comment]
will consider for next update.
